### PR TITLE
Create functon to generate deck of cards

### PR DESCRIPTION
**Pull request by LeonRomo**

### CODE REVIEW

**Comment by mcctor** [comment]
Yo

**Comment by mcctor** [comment]
Okay, so all of this needs to be done in a single python file. And our first step is generating the deck of cards

**Comment by LeonRomo** [comment]
Yes yes..I think that is done but that function called "generate_cards"

**Comment by mcctor** [comment]
What is a card, except for its value? Do we also need the suit of a specific card?

**Comment by LeonRomo** [comment]
No we're only interested in their values....

**Comment by mcctor** [comment]
Oh, and btw, no source file in the repo yet

**Pull request merged**
